"""add conversation summary

Revision ID: 0d1eba22ca9e
Revises: 33d5f083619f
Create Date: 2026-06-22 15:29:44.311732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d1eba22ca9e'
down_revision: Union[str, Sequence[str], None] = '33d5f083619f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('conversation_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'conversation_summary')
    # ### end Alembic commands ###
