"""add search vector

Revision ID: 2853987a6c99
Revises: 241b280bec52
Create Date: 2026-06-23 11:49:34.083378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2853987a6c99'
down_revision: Union[str, Sequence[str], None] = '241b280bec52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'search_vector')
    # ### end Alembic commands ###
