"""add processing status

Revision ID: 77e40dc54554
Revises: 2853987a6c99
Create Date: 2026-06-23 12:38:55.416933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77e40dc54554'
down_revision: Union[str, Sequence[str], None] = '2853987a6c99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_document_chunks_search'), table_name='document_chunks', postgresql_using='gin')
    op.add_column('documents', sa.Column('processing_status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'processing_status')
    op.create_index(op.f('idx_document_chunks_search'), 'document_chunks', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
