"""add chat session metadata

Revision ID: f89ede1fc3f9
Revises: fa1a3964a787
Create Date: 2026-06-22 14:22:43.361364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f89ede1fc3f9'
down_revision: Union[str, Sequence[str], None] = 'fa1a3964a787'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('last_message_at', sa.DateTime(), nullable=True))
    op.add_column('chat_sessions', sa.Column('message_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'message_count')
    op.drop_column('chat_sessions', 'last_message_at')
    # ### end Alembic commands ###
